Remove EWC from docs
StackStorm/st2docs pull request #1020
Opened 2020-09-10 20:00 UTC by amanda11

Update documentation to reflect that EWC is not available after StackStorm 3.2, and that the old enterprise components will be added in future community releases.

Addresses part of #985

2020-09-22 17:08 UTC, amanda11 commented
Given the movement on the enterprise components, going to mark this as draft....

2020-09-28 06:59 UTC, Sheshagiri requested changes
@amanda11 I just rephrased what you already wrote and added a link for reference.

2020-09-28 06:59 UTC, Sheshagiri commented on docs/source/authentication.rst
> +  The EWC components have been gifted to the Linux Foundation, but have not yet been integrated into the StackStorm release.
```suggestion
Extreme Workflow Composer was donated to Linux Foundation, but those components are not yet integrated into the StackStorm release. Please visit https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/ for more details.
```

2020-09-28 06:59 UTC, Sheshagiri commented on docs/source/authentication.rst
> +  Prior to StackStorm 3.3, Extreme Networks provided a commercial version of the StackStorm automation platform including a LDAP auth backend.
```suggestion
  Prior to StackStorm 3.3, Extreme Networks provided a commercial version(Extreme Workflow Composer) of the StackStorm automation platform including an LDAP auth backend.
```

2020-09-28 06:59 UTC, Sheshagiri commented on docs/source/install/common/ewc_intro.rst
> +The EWC components have been gifted to the Linux Foundation, but have not yet been integrated into the StackStorm release.
```suggestion
Extreme Workflow Composer was donated to Linux Foundation, but those components are not yet integrated into the StackStorm release. Please visit https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/ for more details.
```

2020-09-28 06:59 UTC, Sheshagiri commented on docs/source/rbac.rst
> +  The EWC components have been gifted to the Linux Foundation, but have not yet been integrated into the StackStorm release.
```suggestion
Extreme Workflow Composer was donated to Linux Foundation, but those components are not yet integrated into the StackStorm release. Please visit https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/ for more details.
```

2020-09-28 19:38 UTC, Sheshagiri approved these changes
lgtm 👍

2020-09-28 21:06 UTC, armab approved these changes
Thanks @amanda11 and @Sheshagiri!

Looks like we'll need to shelf and revert some of these documentation changes once we fully integrate the enterprise bits in the future st2 releases.

2020-09-28 22:15 UTC, amanda11 commented
> Thanks @amanda11 and @Sheshagiri!
> 
> 
> 
> Looks like we'll need to shelf and revert some of these documentation changes once we fully integrate the enterprise bits in the future st2 releases.

Yes - should be easy to do. I tried to do it so it would be easy to re-instate.

2020-09-28 22:27 UTC, merged