Added upgrade specific instructions for 3.3
StackStorm/st2docs pull request #1028
Opened 2020-10-13 17:51 UTC by nmaludy

Closes #1027 

Adds upgrade specific instructions for:
* MongoDB 4.0 upgrade
* Mistral and Postgres removal

2020-10-13 17:54 UTC, nmaludy commented
Closes #1026

2020-10-13 19:19 UTC, amanda11 requested changes

2020-10-13 19:19 UTC, amanda11 commented on docs/source/install/upgrades.rst
> +* MongoDB 4.0 is the new default version. Previously the version of MongoDB was 3.4 and
The version was only 3.4 before for U16 and EL7. For EL8 and U18 it was already MongoDB 4.0, so the upgrade is only required for some OSes.
Can we add something to state it only applies to those OSes?

2020-10-13 19:19 UTC, amanda11 commented on docs/source/install/upgrades.rst
> +  Ubuntu:
Can we change to Ubuntu 16.04 as not relevant for U18?

2020-10-13 19:19 UTC, amanda11 commented on docs/source/install/upgrades.rst
> +  RHEL/CentOS:
Can we add a comment to say only relevant for RHEL/CentOS 7.x (as for 8.x) we were already at mongodb 4.0.

2020-10-13 19:19 UTC, amanda11 commented on docs/source/install/upgrades.rst
> +  RHEL/CentOS:
Mistral wasn't present on EL8, so can we update this to state it is RHEL/CentOS 7.x?

2020-10-13 19:19 UTC, amanda11 commented on docs/source/install/upgrades.rst
> +  Ubuntu:
Was mistral present on U18? Or should this be Ubuntu 16.04 as title?

2020-10-13 19:22 UTC, amanda11 commented
Looks good, but think we need to make clear that the extra steps are only required for U16 and EL 7, as U18 and EL8 and 3.2.0 used MongoDB 4.0 and didn't have mistral - so therefore no DB upgrade or mistral to remove for the later OSes.

2020-10-16 14:25 UTC, amanda11 commented
Still need to resolve the manual steps for Ubuntu...

2020-10-16 15:12 UTC, amanda11 commented
@nmaludy I got the manual instructions to work on Ubuntu and CentOS. There were a couple of extras I needed on my systems which I have included as notes on the guide:

- on both CentOS and Ubuntu I needed to add the root role to admin
- on Ubuntu I couldn't set the feature compatability version to the upgraded release unless I restarted the mongod service

Ready for review now...

2020-10-16 17:55 UTC, nmaludy commented
@amanda11 this looks great, thank you VERY MUCH!

I can't approve my own PR, so can you approve on your side and we can get it merged?

2020-10-16 20:02 UTC, amanda11 approved these changes
LGTM

2020-10-16 22:14 UTC, amanda11 commented
@nmaludy  Approved, ready to merge when you want

2020-10-16 22:20 UTC, merged