Updated k8s_ha documentation for redis as backend coordination
StackStorm/st2docs pull request #1050
Opened 2021-01-22 02:04 UTC by arms11

2021-01-22 02:04 UTC, arms11 commented
@armab - Please review. Thanks.

2021-01-22 18:05 UTC, armab requested changes
Thanks for updating the st2docs!

A few changes:
- CI is not happy with the syntax. Provided a pointer in the comment above.

- Similar to previous Readme.md changes from your PR: https://github.com/arms11/stackstorm-ha/commit/15abe2fa73c1adc1474b422f11b98ab21dcbd3f0 there are a few more places where we can replace `etcd` with `redis`.

2021-01-22 18:05 UTC, armab commented on docs/source/install/k8s_ha.rst
>  ____
Check the CI failure here:  https://app.circleci.com/pipelines/github/StackStorm/st2docs/278/workflows/623cf438-4d10-406d-9a80-2e8520151f69/jobs/2912

```
Warning, treated as error:
/home/circleci/project/docs/source/install/k8s_ha.rst:305:Title underline too short.
```

2021-01-23 02:52 UTC, arms11 commented
Thanks @armab . Duh...I did not realize there were other references. I replaced them as appropriate. Checked the build also have passed. Please review!

2021-01-23 14:24 UTC, armab approved these changes
Looks good!

Thanks for syncing the Documentation, following the https://github.com/StackStorm/stackstorm-ha/pull/169 change :+1:

2021-01-23 14:25 UTC, merged